/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/Home.vue')['default']
    MarkdownWrapper: typeof import('./src/components/MarkdownWrapper.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavBarHome: typeof import('./src/components/NavBarHome.vue')['default']
    ProejctListHome: typeof import('./src/components/ProejctListHome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
